### ISSUE TITLE
在android 平台不能运行

### ISSUE THREAD

**Issue by wuxiaomo6174** [EricYChu/cordova-plugin-bytedance-union-ad#1]
你好，
感谢提供了穿山甲的插件，第一次使用，我的环境是cordova 9 + cordova-android 10.0 全新空项目，使用了其他插件没有问题，但加了这个插件，就会碰到以下问题，不知道该怎么解决，先谢谢了~

/Users/apple/WebstormProjects/test/platforms/android/app/src/main/java/cordova/plugins/bytedanceunionad/SplashActivity.java:17: 错误: 找不到符号
import androidx.annotation.MainThread;
                          ^
  符号:   类 MainThread
  位置: 程序包 androidx.annotation
/Users/apple/WebstormProjects/test/platforms/android/app/src/main/java/cordova/plugins/bytedanceunionad/SplashActivity.java:104: 错误: 找不到符号
            @MainThread
             ^
  符号: 类 MainThread
/Users/apple/WebstormProjects/test/platforms/android/app/src/main/java/cordova/plugins/bytedanceunionad/SplashActivity.java:113: 错误: 找不到符号
            @MainThread
             ^
  符号: 类 MainThread
/Users/apple/WebstormProjects/test/platforms/android/app/src/main/java/cordova/plugins/bytedanceunionad/SplashActivity.java:122: 错误: 找不到符号
            @MainThread
             ^
  符号: 类 MainThread
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
4 个错误

FAILURE: Build failed with an exception.

**Comment by ericyzhu** [comment]
需要启用 AndroidX 的支持。[官方文档](https://cordova.apache.org/docs/en/10.x/config_ref/index.html#preference)

**Comment by wuxiaomo6174** [comment]
> 需要启用 AndroidX 的支持。[官方文档](https://cordova.apache.org/docs/en/10.x/config_ref/index.html#preference)

是下面这个 对吧？

preference name="AndroidXEnabled" value="true"

开启 和 不开启，我都试过，都不行

**Comment by wuxiaomo6174** [comment]
编译信息中可以看到 启用了 AndroidXEnabled
[Gradle Properties] Detected Gradle property "android.useAndroidX" with the value of "true", Cordova's recommended value is "false"
[Gradle Properties] Detected Gradle property "android.enableJetifier" with the value of "true", Cordova's recommended value is "false"

**Comment by cike987** [comment]
java.lang.RuntimeException: Unable to get provider com.bytedance.sdk.openadsdk.TTFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTFileProvider" on path: DexPathList[[zip file "/data/app/com.abc.efg-y4SaNLKk9kpKsAOpRF8azQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.abc.efg-y4SaNLKk9kpKsAOpRF8azQ==/lib/arm64, /data/app/com.abc.efg-y4SaNLKk9kpKsAOpRF8azQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7907)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7443)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7336)
        at android.app.ActivityThread.access$2400(ActivityThread.java:308)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
        
        
        一运行就报错了
